# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: R

on:
  push:
    branches: [ "master", "newObj" ]
  pull_request:
    branches: [ "master", "newObj" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest,   r: 'release'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up R ${{ matrix.r }}
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - name: Install library on Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install libhdf5-dev
          sudo apt-get install libglpk-dev
          sudo apt-get install pandoc

      - name: Install library on MacOS
        if: runner.os == 'macOS'
        run: |
          brew install hdf5
          brew install pandoc

      - name: Install library on Windows
        if: runner.os == 'Windows'
        run: |
          choco install pandoc

      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck", "covr"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: Check
        run: rcmdcheck::rcmdcheck(args = c("--no-manual"), error_on = "warning")
        shell: Rscript {0}

      - name: Run codecov
        run: |
          covr::codecov()
        shell: Rscript {0}

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3


